travis:
  secure:
    BINSTAR_TOKEN: AxaYVpUUQJH5CYuYUS12J6pkz87x9pZaaw6rvmsiHhQURAUwBv4zf/LHfnq5uMZF79lxcaaXH9oGlspktoLCS72Tv5GmDlnSSksEb0RaPTCEvkIWzEKsPZjNjnxpA7Nre6UX7yWu/ZdIrPJ5H4liUEJqbsJmbfTea9Z/hSUYUcGbkB3vFpn7Ay+I3PGfofTYreAGn2ShAosFwFLJx4cA22k1OVVhO+YySbRbmVBpRjVpSULE9rIEZ2lwLxZRJyQm+L9V2LLcBDUJ1HtzwTbLKYKK9LCZjKZz5yJPapkg96OMt0SkYdy8vWRiz4CvJdBNXLzvgoQEc89gEIluIbHGYyXNm11ov+0ydq05hMmcnbrquDsKPQWBlNSUCf9CMMLj9AZeG5DKBBGafoRCZJWz8jln+oVrvs0iwzJyjo0JXirZDXqtGjtvkzFq8AsPuUEYBBCd+RcGzzHGcRG1YAZeYajwAdStXLj1Vas4kNr+LzeQjaWxrxCpSqj7jV8WDyQ3YWPtAxyG4SUSppVKTCPzZSZ7e7YTTSJX1P1dpkOK/O4phJYq5wH/wvJCDdIVKFLc6sDQxyAq60sfTRFJzVogfy6OX5Y65acjsdRc7AvB7fJ0EStdk9Wm388r+2rXmUP7hjdLowttvqpDkQvlwBD8RfpLc0kEZsdv8IwCjrSrOFM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
